---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - networking.vpccontroller.gcp
  resources:
  - vpccontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.vpccontroller.gcp
  resources:
  - vpccontrollers/finalizers
  verbs:
  - update
- apiGroups:
  - networking.vpccontroller.gcp
  resources:
  - vpccontrollers/status
  verbs:
  - get
  - patch
  - update
