apiVersion: networking.github.com/v1
kind: VPCController
metadata:
  labels:
    app.kubernetes.io/name: vpc-controller
    app.kubernetes.io/managed-by: kustomize
  name: vpccontroller-sample
spec:
  # TODO(user): Add fields here
